#!/bin/sh
# Trigger MunkiReport server to do a lookup from Kandji

# Skip manual check
if [ "$1" = 'manualcheck' ]; then
	echo 'Manual check: skipping'
	exit 0
fi

# Check if Jamf binary is installed
if [ ! -e "/usr/local/bin/kandji" ] && [ ! -e "/Library/Kandji/Kandji Agent.app/Contents/MacOS/kandji-cli" ]; then
    echo "The Kandji binary doesn't appear to be installed. Is it enrolled?"
    exit 0
fi

# Get preference for Kandji checks, if exists
CHECK=$(defaults read /Library/Preferences/MunkiReport KandjiCheck 2>/dev/null)

# If set to 0, disable automatic Kandji lookups for this machine
if [[ ${CHECK} == "0" ]] ; then
    echo "Kandji lookups for this machine are disabled."
    exit 0
else
    # Make sure the cache directory exists
    DIR=$(dirname $0)
    mkdir -p "$DIR/cache"

    # Store date in file to trigger Kandji lookup
    date > "$DIR/cache/kandji.txt"
fi
